### ISSUE TITLE
Some Clarifications on the Running configurations for Stage1 and Stage2

### ISSUE THREAD

**Issue by varun-krishnaps** [TaoRuijie/Loss-Gated-Learning#11]
1. **For Stage1** : In the paper it is mentioned that batch size used is 256 and learning rate decays by 5% every 5 epochs, but in the code batch size is 300 and learning rate decays by 10% every 5 epochs
2.  **For Stage2 ** : In the code "main_train.py" of Stage2, it is mentioned that **gates = [1, 3, 3, 5, 6] # Set the gates in each iterations, which is different from our paper because we use stronger augmentation in dataloader** 

**What should be the right the configurations for stage1 and stage2 to reproduce the results?**
**Currently in the stage1, my EER doesn't go below 8.13**

**Comment by TaoRuijie** [comment]
1. I train the model for these two settings, they get the same results with EER = 7.36, in my experiments that did not affect the performance.

2. I remember in this code, [1,3,3,5,6] is slightly better so I put in for open-source version after publication.

**Comment by varun-krishnaps** [comment]
Hi Tao,

Can you please share the model of Stage 2 just like you did for Stage 1 ??

Thank you

**Comment by TaoRuijie** [comment]
Here ...

**Comment by TaoRuijie** [comment]
https://drive.google.com/file/d/1VLTbAPYwDV7YJPkLz-4pJbAPkGre1YvZ/view?usp=sharing

Here is it..

**Comment by varun-krishnaps** [comment]
Thanks a lot Tao

**Comment by varun-krishnaps** [comment]
Hi Tao, 
 The model you shared in the link seems to be corrupted....while i load it using the i get the error *RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory*.

Can u check your model file again ??

**Comment by varun-krishnaps** [comment]
Hi Tao,

I was able to reproduce the Stage 2 Results....Actually I am able to get EER = 1.53 

Thanks a lot for your code
