### ISSUE TITLE
结果反馈

### ISSUE THREAD

**Issue by gaonan98** [TaoRuijie/Loss-Gated-Learning#12]
小黑哥我跑完了你修改后开源的代码，看到你b站上说希望大家跑完贴在issue里让你也看看，我训练挺久EER才到2%Y以下。再次感谢你能开源这份工作和你平常的指导，谢谢！
![微信截图_20240111211055](https://github.com/TaoRuijie/Loss-Gated-Learning/assets/61961696/19e9d728-ec26-41d6-a3f5-c9b62c7b04b1)

**Comment by TaoRuijie** [comment]
感谢分享！你最后这个是不是没有换成C=1024的大的ecapa啊？我c=512的时候也是大概就2左右的eer

前两天有个用户说可以到1.53最后 

![image](https://github.com/TaoRuijie/Loss-Gated-Learning/assets/45703754/64005931-0bd2-4deb-acea-9ab40d08bfd8)

**Comment by gaonan98** [comment]
> 感谢分享！你最后这个是不是没有换成C=1024的大的ecapa啊？我c=512的时候也是大概就2左右的eer
> 
> 前两天有个用户说可以到1.53最后
> 
> ![image](https://private-user-images.githubusercontent.com/45703754/295925568-64005931-0bd2-4deb-acea-9ab40d08bfd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5Nzk1NTEsIm5iZiI6MTcwNDk3OTI1MSwicGF0aCI6Ii80NTcwMzc1NC8yOTU5MjU1NjgtNjQwMDU5MzEtMGJkMi00ZGViLWFjZWEtOWFiNDBkMDhiZmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDEzMjA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNmM5ODE3NGZjMWNmY2ZkNjQ0NWZmNjhlY2FjNWZkYmMxMDVhZGI0NTkzNWQzNzA1Y2E3NDYyYjUyMWNhOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iUkc_MFXmJrY2a00dbY2i85OUfDXL19bQZ9gOb_4p0o)

确实，不好意思。看来这个C换成1024效果会好很多

**Comment by TaoRuijie** [comment]
嗯嗯是的，最后一个iteration换个大点的模型 不然到最后一个了已经没啥变化了

**Comment by 1090114998** [comment]
小黑哥，感谢您开源的代码，对我的学习有很大的帮助！但是我有个问题，按照您给的代码，如果直接将iteration 5的通道更换成1024，那么初始模型就没法读取了，所以，扩充通道的具体步骤是什么呢？就是直接使用一个随机初始化的通道数为1024的模型进行训练嘛？

**Comment by TaoRuijie** [comment]
对的 最后直接train

**Comment by 1090114998** [comment]
感谢小黑哥的解答！
