### ISSUE TITLE
求预训练好的模型

### ISSUE THREAD

**Issue by PunkMale** [TaoRuijie/Loss-Gated-Learning#13]
小黑哥您好，近期需要参考您之前的工作，您的LGL报道了Vox-O、E、H的结果，我们想进一步测试一下在SITW数据集上的结果，不知您之前的模型是否还保存着？如果有的话希望您能共享一下。感谢🙏

**Comment by TaoRuijie** [comment]
https://github.com/TaoRuijie/Loss-Gated-Learning/issues/11#issuecomment-1874952166

应该是这个

**Comment by PunkMale** [comment]
感谢您的回复！
我遇到了和那位老哥一样的问题：
`RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`
您是否方便在自己的设备上检查一下该文件是否能正常读取？感谢🙏

**Comment by TaoRuijie** [comment]
https://drive.google.com/file/d/1YvE7FxJ3QNlIx29rH-Gxmvns2NhW-29B/view?usp=sharing

如果还不可以请给我邮箱 我发邮箱试试

**Comment by gaonan98** [comment]
> https://drive.google.com/file/d/1YvE7FxJ3QNlIx29rH-Gxmvns2NhW-29B/view?usp=sharing
> 
> 如果还不可以请给我邮箱 我发邮箱试试

小黑哥我用了上述链接将它放在Stage1中进行测试，仍然是报`RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`这样的错误 能否给我邮箱中发一份 gaonan98@qq.com 谢谢

**Comment by PunkMale** [comment]
> > https://drive.google.com/file/d/1YvE7FxJ3QNlIx29rH-Gxmvns2NhW-29B/view?usp=sharing
> > 如果还不可以请给我邮箱 我发邮箱试试
> 
> 小黑哥我用了上述链接将它放在Stage1中进行测试，仍然是报`RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`这样的错误 能否给我邮箱中发一份 [gaonan98@qq.com](mailto:gaonan98@qq.com) 谢谢

小黑哥之前给我发的py文件可以用，我发你。

**Comment by gaonan98** [comment]
谢谢大哥



---原始邮件---
发件人: "Zhihua ***@***.***&gt;
发送时间: 2024年3月14日(周四) 凌晨0:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TaoRuijie/Loss-Gated-Learning] 求预训练好的模型 (Issue #13)




   
https://drive.google.com/file/d/1YvE7FxJ3QNlIx29rH-Gxmvns2NhW-29B/view?usp=sharing
 如果还不可以请给我邮箱 我发邮箱试试
  
小黑哥我用了上述链接将它放在Stage1中进行测试，仍然是报RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory这样的错误 能否给我邮箱中发一份 ***@***.*** 谢谢
  
小黑哥之前给我发的py文件可以用，我发你。

**Comment by TaoRuijie** [comment]
谢谢！:)

**Comment by gaonan98** [comment]
小黑哥在第二阶段中，你是根据测试集效果来判定普通训练和 LGL是否要停的时机 这算不算是加入了一些监督信息啊

**Comment by TaoRuijie** [comment]
那个是validation set啊 文章里应该有说

**Comment by gaonan98** [comment]
我觉得哪怕验证集也是引入了标签信息，您能跟我详细说说你的理解吗



---原始邮件---
发件人: "Tao ***@***.***&gt;
发送时间: 2024年3月14日(周四) 下午5:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TaoRuijie/Loss-Gated-Learning] 求预训练好的模型 (Issue #13)




 
那个是validation set啊 文章里应该有说

**Comment by TaoRuijie** [comment]
以下是我个人的想法
1. 我觉得自监督学习目的是利用没标签的数据训练出一个好模型，但必须要有一个判定好模型的标准，于是有了validation和test 前者是得到集内的performance，后者是得到通用的performance。但有并且用这个validation set找到最好的模型这件事情我觉得和自监督不冲突
2. 反推一下呐，有验证集是来衡量模型学的好坏的，如果按你的理解的话，之前包括之后的所有自监督声纹识别的工作都无法操作了，因为不仅stage2，stage1也需要一个东西告诉模型什么时候要停下来。只看training loss是显然不行的
3. validation数据和training数据相互独立 没有重合
4. 参考所有声纹识别比赛，尤其是self-supervised track，一定会给出validation set来给参赛者验证模型的好坏，参赛者可以通过这个validation performance调节模型选择参数等等。这是同理的
5. 退一步来说，vox1-o只包含3K数据40个人左右，和总数据量1000K，6000个人 相比也并不能起不到很大的监督

**Comment by gaonan98** [comment]
谢谢小黑哥 我还有个问题就是如果你用 O 来做验证集，严格来讲最后测试的时候是不是不可以用 O 来测试了 只能用 EH 来测试



---原始邮件---
发件人: "Tao ***@***.***&gt;
发送时间: 2024年3月14日(周四) 晚上6:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TaoRuijie/Loss-Gated-Learning] 求预训练好的模型 (Issue #13)




 
以下是我个人的想法
  
我觉得自监督学习目的是利用没标签的数据训练出一个好模型，但必须要有一个判定好模型的标准，于是有了validation和test 前者是得到集内的performance，后者是得到通用的performance。但有并且用这个validation set找到最好的模型这件事情我觉得和自监督不冲突
 
反推一下呐，有验证集是来衡量模型学的好坏的，如果按你的理解的话，之前包括之后的所有自监督声纹识别的工作都无法操作了，因为不仅stage2，stage1也需要一个东西告诉模型什么时候要停下来。只看training loss是显然不行的
 
validation数据和training数据相互独立 没有重合
 
参考所有声纹识别比赛，尤其是self-supervised track，一定会给出validation set来给参赛者验证模型的好坏，参赛者可以通过这个validation performance调节模型选择参数等等。这是同理的
 
退一步来说，vox1-o只包含3K数据40个人左右，和总数据量1000K，6000个人 相比也并不能起不到很大的监督

**Comment by gaonan98** [comment]
我有一个想法，能否在每一轮训练结束后只做聚类然后找一种不用借助标签的聚类评分方法来代替根据验证集上的性能，用这个来控制训练什么时候停



---原始邮件---
发件人: "Tao ***@***.***&gt;
发送时间: 2024年3月14日(周四) 晚上6:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TaoRuijie/Loss-Gated-Learning] 求预训练好的模型 (Issue #13)




 
以下是我个人的想法
  
我觉得自监督学习目的是利用没标签的数据训练出一个好模型，但必须要有一个判定好模型的标准，于是有了validation和test 前者是得到集内的performance，后者是得到通用的performance。但有并且用这个validation set找到最好的模型这件事情我觉得和自监督不冲突
 
反推一下呐，有验证集是来衡量模型学的好坏的，如果按你的理解的话，之前包括之后的所有自监督声纹识别的工作都无法操作了，因为不仅stage2，stage1也需要一个东西告诉模型什么时候要停下来。只看training loss是显然不行的
 
validation数据和training数据相互独立 没有重合
 
参考所有声纹识别比赛，尤其是self-supervised track，一定会给出validation set来给参赛者验证模型的好坏，参赛者可以通过这个validation performance调节模型选择参数等等。这是同理的
 
退一步来说，vox1-o只包含3K数据40个人左右，和总数据量1000K，6000个人 相比也并不能起不到很大的监督
