### ISSUE TITLE
About Vox_O, Vox_E, Vox_H sets

### ISSUE THREAD

**Issue by xjchenGit** [TaoRuijie/Loss-Gated-Learning#2]
Thank you for providing code, which can help me follow your work to further research. However, I have some confuse about the setting of Vox_O, Vox_E, Vox_H. According to your GitHub repo. It seems that you use the cleaned version of Vox_O, Vox_E, Vox_H for evaluation, but your reference “An iterative framework for self-supervised deep speaker representation learning.” is use the version without “cleaned” notation. What is the difference between this two version evaluation set ? Hope your reply, which is helpful for me. Thanks!

**Comment by TaoRuijie** [comment]
Clean is the txt file with the index "2"   Please check it on voxceleb dataset website. It has metioned.

For the paper you mentioned. I do not know they use which version.

Clean list removes some wrong trials. So EER can be a bit better(about5% to10% I remember)
