### ISSUE TITLE
关于stage2的main.PY

### ISSUE THREAD

**Issue by jzz990415** [TaoRuijie/Loss-Gated-Learning#5]
您好，非常感谢您能开源代码，我发现在stage2的时候您是将判断下一个状态的代码写在了循环epoch里面，那如果假设withoutLGL的训练一直都有效，没有进入到LGL就达到了max epoch的情况呢

**Comment by TaoRuijie** [comment]
有可能会吧，我开始写代码的时候是手动做这个iteration的循环的 后来觉得有点麻烦所以写出这样了，可以把max epoch做大一点

**Comment by jzz990415** [comment]
好的谢谢这么及时的回复
