### ISSUE TITLE
在Stage1中无法读取文件

### ISSUE THREAD

**Issue by gaonan98** [TaoRuijie/Loss-Gated-Learning#6]
感谢小黑哥开源代码，刚开始的时候报的错误是`soundfile.LibsndfileError: <exception str() failed>`，经过查阅后我把soudfile的版本修改到了0.10.3.post1，但是又出现了如下错误，代码刚开始能跑，过了几分钟就开始报错了，不知道是什么原因造成的？
![image](https://user-images.githubusercontent.com/61961696/236986002-c8b3e533-460d-4ff0-8ebd-65ed8fd97874.png)

顺便问一句，我看到的代码使用musan数据集时都是以musan_split命名的，但是我发现貌似它只是将musan中的README等解释文件删除了，还是它有什么其他修改的地方吗？

**Comment by TaoRuijie** [comment]
这个应该是你的数据准备的问题，对应的文件路径上没有

musan的数据准备代码在这里：

https://github.com/clovaai/voxceleb_trainer/blob/master/dataprep.py#L151

按照这个做一样的就好了，

**Comment by gaonan98** [comment]
好的好的，谢谢大哥，我这就去试试

**Comment by gaonan98** [comment]
我按照您给的准备代码重新处理了musan数据，程序已经能够正常运行，看来就是musan数据集的问题，感谢大佬！
