### ISSUE TITLE
about stage 1

### ISSUE THREAD

**Issue by JINzezhong7** [TaoRuijie/Loss-Gated-Learning#7]
Thank you for the open-source code. I want to use the stage1 code. but when I run stage 1 using the voxceleb2 dataset, it error occurs.
![image](https://github.com/TaoRuijie/Loss-Gated-Learning/assets/131787594/a6c41d75-f53c-4d68-8ae6-730ea131eb79)
I didn't know why.

**Comment by TaoRuijie** [comment]
I guess you change the code for dataloader class and miss involving one argument. From the screenshot I cannot know the details.

**Comment by JINzezhong7** [comment]
thank you, is the rir path
