### ISSUE TITLE
double free or corruption (out)

### ISSUE THREAD

**Issue by gaonan98** [TaoRuijie/Loss-Gated-Learning#8]
在StageⅡ经常跑到一半会显示double free or corruption (out)的错误，请问这种问题该怎么解决？
![image](https://github.com/TaoRuijie/Loss-Gated-Learning/assets/61961696/e73db245-ffdc-47fa-879a-51348920e727)

**Comment by TaoRuijie** [comment]
这个问题我没有遇到过，应该是聚类的过程中使用faiss库出现的问题，看起来和gpu的显存有关

https://github.com/facebookresearch/faiss/issues/2537#issuecomment-1296156856

**Comment by gaonan98** [comment]
好的，感谢你的回答，那看来目前的办法就只能减小batchsize了

**Comment by TaoRuijie** [comment]
但你这一步是提取完了feature然后聚类的时候报错吧，和batchsize感觉没有关系

因为这可能是个hardware带来的问题，所以我没有好的解决方法。

也许你可以尝试减少聚类的数据量，看看是不是就没有报错了。

**Comment by gaonan98** [comment]
我所用的显卡为A100,因为同时也有其他人在用所以显存可能不够。感谢您提出的宝贵建议，我去尝试一下减少聚类的数据量。

从 Windows 版邮件发送

发件人: Tao Ruijie
发送时间: 2023年5月30日 9:37
收件人: TaoRuijie/Loss-Gated-Learning
抄送: GaoNan; Author
主题: Re: [TaoRuijie/Loss-Gated-Learning] double free or corruption (out)(Issue #8)

但你这一步是提取完了feature然后聚类的时候报错吧，和batchsize感觉没有关系
因为这可能是个hardware带来的问题，所以我没有好的解决方法。
也许你可以尝试减少聚类的数据量，看看是不是就没有报错了。
